### ISSUE TITLE
SNYK-JS-ADMZIP-1065796: Update cassandra-driver to 4.6.2

### ISSUE THREAD

**Issue by candrews** [sqlpad/sqlpad#1000]
sqlpad 6.5.0 depends on `cassandra-driver@4.6.1` which depends on `adm-zip@0.4.16` which has a vulnerability, https://snyk.io/vuln/SNYK-JS-ADMZIP-1065796

Can you please update `cassandra-driver` to `4.6.1` which addresses this issue? https://github.com/datastax/nodejs-driver/blob/v4.6.2/CHANGELOG.md#462

**Comment by rickbergfalk** [comment]
This is fixed in `latest`/`6.6.0`
