### ISSUE TITLE
Increase login expiration time

### ISSUE THREAD

**Issue by CrashLaker** [sqlpad/sqlpad#1007]
Hi all,

How can I increase `SQLPAD_SESSION_MINUTES` via container?

https://github.com/sqlpad/sqlpad/blob/master/docs/configuration.md
default is
```
SQLPAD_SESSION_MINUTES = 60
```

**Comment by rickbergfalk** [comment]
Depend on how you are running the container. If using docker-compose you can set via environment variable like so https://github.com/sqlpad/sqlpad/blob/master/docker-examples/postgres-docker-compose/docker-compose.yml#L19. 

If using docker cli, you can use the --env -e or --env-file arguments.

**Comment by CrashLaker** [comment]
thank you it worked. `-e SQLPAD_SESSION_MINUTES=99999`
i was using an old image from ages ago.
there's been many changes to the UI since i last saw it. 
congrats :)
