### ISSUE TITLE
Driver for Amazon Athena

### ISSUE THREAD

**Issue by ssedano** [sqlpad/sqlpad#1008]
Hi team,

I'd like to contribute a driver for Amazon Athena. And before discussing specifics, I'd like to know if the community would be interested in the contribution.

Thank you.

**Comment by rickbergfalk** [comment]
Definitely! Always happy to expand database support.

**Comment by ssedano** [comment]
Great news, thanks.

I'd like to discuss a change in the driver interface to include an optional method to cancel queries. Cancelling queries it's a very important feature since it stops customers being charged for queries that they no longer care about or queries run by mistake.

I propose to extend the driver data model to include a flag indicating that the driver implements a method to cancel queries. The client would render a "cancel query" button, disabled when the query is not running, if the driver has this flag set.

Thoughts?

**Comment by rickbergfalk** [comment]
That would be awesome! I'm in full support of that and I feel like its been requested in the past. Just never prioritized it since most drivers don't have support for it. Makes a lot of sense for these cloud platforms though.

> I propose to extend the driver data model to include a flag indicating that the driver implements a method to cancel queries. The client would render a "cancel query" button, disabled when the query is not running, if the driver has this flag set.

This is perfect. Something similar is already done for the "connection client" support.

**Comment by acountrec** [comment]
Very open for it! Could you please include the option to assume role and with mfa support?

**Comment by ssedano** [comment]
Apologies for the delay on this. I expect to have a first version ready by end of next week.

That first version will use instance profile to obtain credentials. We can discuss other options for authentication when the pull request is open for review.

**Comment by pvieito** [comment]
Any update on this? We are extremely interested on Amazon Athena support.

**Comment by pvieito** [comment]
Hi! I've just created a new PR to add support for Athena in SQLPad: https://github.com/sqlpad/sqlpad/pull/1044
