### ISSUE TITLE
Add useHTTPS checkbox for Trino similar to Presto

### ISSUE THREAD

**Issue by muRn** [sqlpad/sqlpad#1017]
Idea comes from #997. We are having a problem connecting Sqlpad to our Trino instance because Sqlpad tries to use http while our instance is behind https. I can make a change myself, I just wanted to confirm there are no objections.

**Comment by rickbergfalk** [comment]
Hi @muRn - would gladly pull this in if you wanted to open a PR! same approach should be fine.
