### ISSUE TITLE
what's the default password of docker example

### ISSUE THREAD

**Issue by geosmart** [sqlpad/sqlpad#1020]
when run `docker run -p 3000:3000 sqlpad/sqlpad:latest`

what's the default password of docker example 

![image](https://user-images.githubusercontent.com/3156608/121666626-0b87d800-cadc-11eb-8d1a-cb6831106c62.png)

just want to  try sqlpad

**Comment by rickbergfalk** [comment]
Hi @geosmart -- there isn't one by default. You must provide an initial user with environment variables `SQLPAD_ADMIN` for email, `SQLPAD_ADMIN_PASSWORD` for password.

You can also disable auth if you'd like https://sqlpad.github.io/sqlpad/#/authentication?id=no-authentication

**Comment by geosmart** [comment]
thanks

so with docker just add the `--env` make it working
 
```
sudo docker run -p 3000:3000 --env SQLPAD_ADMIN=admin --env SQLPAD_ADMIN_PASSWORD=123 sqlpad/sqlpad:latest 
```
