### ISSUE TITLE
Error when using MariaDB as backend database

### ISSUE THREAD

**Issue by muRn** [sqlpad/sqlpad#1026]
I was experimenting with sqlpad lately and everything was working fine up until the point when I decided to have standalone backend database for query history persistence. First DBMS I tried was MariaDB (simply because I had a spare one) and after I created separate schema for sqlpad there and pointed `SQLPAD_BACKEND_DB_URI` variable to it I was left with only auth working. Both schema browser and queries stopped working. In the logs of sqlpad I see that it's trying to read something from `batches` table and failing:
```
{"level":20,"time":"2021-06-17T11:05:48.431Z","pid":1,"hostname":"51b5bfe1a4ad","name":"sqlpad-app","msg":"Executing (default): SELECT `id`, `query_id` AS `queryId`, `name`, `connection_id` AS `connectionId`, `connection_client_id` AS `connectionClientId`, `status`, `start_time` AS `startTime`, `stop_time` AS `stopTime`, `duration_ms` AS `durationMs`, `batch_text` AS `batchText`, `selected_text` AS `selectedText`, `chart`, `user_id` AS `userId`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `batches` AS `Batches` WHERE `Batches`.`id` = 'b762439e-0674-4325-8d69-1136b6376322';"}
{"level":50,"time":"2021-06-17T11:05:48.435Z","pid":1,"hostname":"51b5bfe1a4ad","name":"sqlpad-app","stack":"SyntaxError: Unexpected token o in JSON at position 1
  at JSON.parse (<anonymous>)
  at /usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:186:72
  at Array.map (<anonymous>)
  at Query.handleJsonSelectQuery (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:185:21)
  at Query.formatResults (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:130:12)
  at Query.run (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:74:17)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async /usr/app/node_modules/sequelize/lib/sequelize.js:619:16
  at async MySQLQueryInterface.select (/usr/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
  at async Function.findAll (/usr/app/node_modules/sequelize/lib/model.js:1753:21)
  at async Function.findOne (/usr/app/node_modules/sequelize/lib/model.js:1917:12)
  at async Batches.findOneById (/usr/app/models/batches.js:16:17)
  at async create (/usr/app/routes/batches.js:38:20)","type":"Error","msg":"Unexpected token o in JSON at position 1"}
```

Then I tried to use postgres as backend db and it worked perfectly fine! I see the same query from `batches` table except now it's not failing:
```
{"level":20,"time":"2021-06-17T11:49:13.826Z","pid":1,"hostname":"49cf75db16ed","name":"sqlpad-app","msg":"Executing (default): SELECT \"id\", \"query_id\" AS \"queryId\", \"name\", \"connection_id\" AS \"connectionId\", \"connection_client_id\" AS \"connectionClientId\", \"status\", \"start_time\" AS \"startTime\", \"stop_time\" AS \"stopTime\", \"duration_ms\" AS \"durationMs\", \"batch_text\" AS \"batchText\", \"selected_text\" AS \"selectedText\", \"chart\", \"user_id\" AS \"userId\", \"created_at\" AS \"createdAt\", \"updated_at\" AS \"updatedAt\" FROM \"batches\" AS \"Batches\" WHERE \"Batches\".\"id\" = '6e2b517a-e508-4064-9bca-bb63dff94b87';"}
{"level":20,"time":"2021-06-17T11:49:13.832Z","pid":1,"hostname":"49cf75db16ed","name":"sqlpad-app","msg":"Executing (default): SELECT \"id\", \"query_id\" AS \"queryId\", \"name\", \"connection_id\" AS \"connectionId\", \"connection_client_id\" AS \"connectionClientId\", \"status\", \"start_time\" AS \"startTime\", \"stop_time\" AS \"stopTime\", \"duration_ms\" AS \"durationMs\", \"batch_text\" AS \"batchText\", \"selected_text\" AS \"selectedText\", \"chart\", \"user_id\" AS \"userId\", \"created_at\" AS \"createdAt\", \"updated_at\" AS \"updatedAt\" FROM \"batches\" AS \"Batches\" WHERE \"Batches\".\"id\" = '6e2b517a-e508-4064-9bca-bb63dff94b87';"}
```

I thought may be I misconfigured something in the first place so I decided to reproduce everything from scratch and... Managed to do that: combo of latest `sqlpad` docker image + latest `mariadb` docker image + `SQLPAD_BACKEND_DB_URI` pointing to that mariadb is definitely not working as it should.

Any ideas what could cause this behavior?

**Comment by eladeyal-intel** [comment]
just to be on the safe side, here's the CI using "latest mariadb docker image" --> https://github.com/sqlpad/sqlpad/pull/1027/checks

**Comment by eladeyal-intel** [comment]
Wow that escalated quickly

![image](https://user-images.githubusercontent.com/20379005/122422152-9877d900-cf95-11eb-81ac-44137597aaf4.png)

**Comment by eladeyal-intel** [comment]
I wonder if it has anything to do with the below

https://github.com/sequelize/sequelize/issues/12583

https://github.com/sequelize/sequelize/pull/13273

**Comment by muRn** [comment]
Looks like first issue you mentioned is the one to blame. I've tested few different MariaDB versions as backend db for sqlpad:
10.4.19 - everything is working fine 👌
10.5.1 - everything is working fine 👌
10.5.2 - error from first post
10.5.3 - same error from first post
10.5.5 - same error from first post
10.5.9 (which was wrongly tagged as latest on my machine) - same error from first post
10.5.10 - different error (below), sqlpad container fails to start, so with this version even auth screen is not working :)
```
{"level":50,"time":"2021-06-17T17:15:40.741Z","pid":1,"hostname":"40a0b78d0401","name":"sqlpad-app","name":"SequelizeDatabaseError","parent":{"fatal":false,"errno":1054,"sqlState":"42S22","code":"ER_BAD_FIELD_ERROR","sql":"ALTER TABLE `users` ADD `sync_auth_role` TINYINT(1);"},"original":{"fatal":false,"errno":1054,"sqlState":"42S22","code":"ER_BAD_FIELD_ERROR","sql":"ALTER TABLE `users` ADD `sync_auth_role` TINYINT(1);"},"sql":"ALTER TABLE `users` ADD `sync_auth_role` TINYINT(1);","stack":"SequelizeDatabaseError: (conn=8, no: 1054, SQLState: 42S22) Unknown column '`sqlpad`.`u`.`data`' in 'CHECK'\nsql: ALTER TABLE `users` ADD `sync_auth_role` TINYINT(1); - parameters:[]\n    at Query.formatError (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:277:16)\n    at Query.run (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:66:18)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","type":"Error","msg":"Error starting SQLPad"}
```

**Comment by eladeyal-intel** [comment]
@rickbergfalk  ... This comment https://github.com/sequelize/sequelize/issues/12583#issuecomment-817193937 suggests adding a dialect Option.
```
const sequelize = new Sequelize(..., {
  dialectOptions: { autoJsonMap: false }
});
```

I think I tried but couldn't find where to put this in sqlpad code.

Have we tested using sqlpad to access a mariadb latest DB (as a connection, not as a backend database) ?

**Comment by rickbergfalk** [comment]
Didn't mean to close this via the reference in the PR 😅 

Thanks for reporting this @muRn and the investigation @eladeyal-intel. The linked sequelize issue/PR looks like it was the underlying problem.

I went ahead and forked sequelize, made the suggested fixes, and published it under a scoped npm package, then imported/aliased sequelize in SQLPad to use that version instead.

I think this fixes the issue. CI tests are passing at least. 

@muRn I'd ask you to validate the new changes, but it seems SQLPad's dockerhub integration has been disabled due to some changes :(.

Will try to get that up and running again and will post when latest docker image is updated with latest fix.

**Comment by eladeyal-intel** [comment]
Docker hub suspended automatic builds for free accouns.

https://docs.docker.com/docker-hub/builds/

You can 

1. Apply to be recognized as an open source project and then supposedly get it back (see link in that document above)

2. Build with GitHub actions and then push the built image to docker hub vis GitHub actions.

3. Dump dockerhub, use GitHub new repository (beta)

**Comment by rickbergfalk** [comment]
Was just typing as you posted - I've submitted an application. If denied will probably look into using actions to build and publish there.

**Comment by muRn** [comment]
I've tested latest sqlpad with my configuration, it's working now!

@rickbergfalk You probably would like to merge your change back to sequelize now? One of sequelize reviewers [already agreed](https://github.com/sequelize/sequelize/pull/13273#pullrequestreview-671786437) to similar change, but PR author disappeared. I think he'll be glad to merge your changes instead :)

P.S. I've also tested [another way to fix the issue](https://github.com/muRn/sqlpad/commit/c49258243626f19cfca0ab24bad0cb0e84ae7697) and it's also working. So if sequelize team refuses to merge your change for some reason and you don't want to maintain your own fork of sequelize - you may consider this option :)

**Comment by rickbergfalk** [comment]
Sequelize seems to be maintained again 🙌 Was able to get the changes in the fork back upstream https://github.com/sequelize/sequelize/pull/13633
