### ISSUE TITLE
Issue when authenticate with Azure Active Direcroty

### ISSUE THREAD

**Issue by baoduy** [sqlpad/sqlpad#1039]
Hi All
I'm setting up the authentication for sqlpad with Azure AD. However, I got the below error and don't know how to fix it yet.

```
:"/auth/oidc/callback?error=invalid_client&error_description=AADSTS650053: The application asked for scope 'roles' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'.
```

**Comment by mqueb** [comment]
seem SQLPAD_OIDC_SCOPE is ignore.
i have that issue:
`GET /auth/oidc/callback?error=invalid_scope&error_description=email%20is%20invalid.%20Please%20use%20a%20valid%20scope%20name%20in%20the%20`
and have set:
`SQLPAD_OIDC_SCOPE: "openid profile user_attributes roles"`
