### ISSUE TITLE
Queries sidebar no longer scrollable

### ISSUE THREAD

**Issue by sirianni** [sqlpad/sqlpad#1043]
After upgrading to sqlpad 6.x I'm no longer able to scroll through the list of saved queries (if it exceeds what's visible).  This worked previously on 5.x.

I'm able to use the search box to find a query, so I know the queries are still present on the backend.

**Comment by rickbergfalk** [comment]
Hi @sirianni - which version of SQLPad, browser, and OS are you running? On SQLPad 6.7, latest Chrome, windows 10, queries list is scrollable.

**Comment by sirianni** [comment]
I am running SQLPad 6.7.1 with Chrome 93.0.4577.63 on Linux.  I see the same issue on the latest Firefox.

It looks like the XHR only requests 20 queries, so I'm assuming there's some lazy pagination going on behind the scenes...?

I do see scroll bars if I shrink the height so that the 20 queries are shown, but it still doesn't fetch more queries if I scroll to the bottom.  Since there are only 20 elements in the DOM, I can understand why the browser is not showing scroll bars if they all fit.

**Comment by sirianni** [comment]
We've upgraded to 6.11 and this seems to have been fixed.
