### ISSUE TITLE
this guy is using the name but not the tool ?

### ISSUE THREAD

**Issue by eladeyal-intel** [sqlpad/sqlpad#1050]
https://www.reddit.com/r/SQL/comments/oox8qk/hi_i_am_the_founder_of_sqlpadio_ama/

https://sqlpad.io/

**Comment by rickbergfalk** [comment]
I suppose reusing SQLPad's name probably gets him lots of free search traffic. He seems quick to also point out he was Apple. All feels a bit gross if you ask me.

**Comment by rickbergfalk** [comment]
Well I don't know where this is going but https://twitter.com/DataLeonWei/status/1425499980995825667

**Comment by rickbergfalk** [comment]
Reached out to sqlpad.io's creator. He says he has no ill intentions towards this open source project and that the name was initially thought of from https://coderpad.io/, which makes sense.

Kind of a bummer as this will make it harder for people to find this open source project if someone searches for it, but its not like it is a super creative name either 😅 

Decided to purchase "getsqlpad.com" so there's an easier address for people to share and remember if they are so inclined to share. Should have probably done that long ago...

**Comment by eladeyal-intel** [comment]
@rickbergfalk :-( :-( :-( TTBOMK He can't get a US trademark if you've been using this name before and the product was known with that name long before. He should have googled "sqlpad" before applying.  Just find the oldest public mention/release of sqlpad with that name and get into some arrangement. It's not right for people to stampede on open source projects. A quick glance suggest that transferring a trademark is only USD30?

**Comment by rickbergfalk** [comment]
Yeah it is unfortunate :(

On the upside... I'm not a legal expert but it is very likely SQLPad the open-source project is protected and the trademark is not enforceable. Amazed US Trademark people don't bother to google 🙃 

https://google.github.io/opencasebook/trademarks/#common-law-trademarks
