### ISSUE TITLE
Docker images are not updated

### ISSUE THREAD

**Issue by pvieito** [sqlpad/sqlpad#1060]
Hi! On the [project README](https://github.com/sqlpad/sqlpad#readme) is stated the following:

> `latest` tag is continuously built from latest commit in repo. Only use that if you want to live on the edge, otherwise use specific version tags to ensure stability.

But the last update to [the current `latest ` tag is a month old](https://hub.docker.com/r/sqlpad/sqlpad/tags?page=1&ordering=last_updated), and the last release `6.8.0` has not been published as a Docker image.

Is there any issue in the CI?

**Comment by rickbergfalk** [comment]
Thanks for the heads up! There must be. I'll see if I can get this fixed

**Comment by rickbergfalk** [comment]
Docker removed the automated builds for the free open source plan :(

**Comment by rickbergfalk** [comment]
Latest image is being built by GitHub actions now 🎉 

Getting tag builds set up now

**Comment by rickbergfalk** [comment]
Now we have docker tags for versions, branches, git shas... more docker tags than we probably need 😅 

Thanks again for reporting @pvieito!

**Comment by pvieito** [comment]
Great, thank you!
