### ISSUE TITLE
Integration of SQLPad Web App with Jupyter-Server-Proxy?

### ISSUE THREAD

**Issue by atnjqt** [sqlpad/sqlpad#1099]
Hi SQLPad team,

This is really an enhancement request, is there any consideration on providing a simple Jupyter-Server-Proxy implementation for hosting SQLPad through Jupyterhub? More information is here https://github.com/jupyterhub/jupyter-server-proxy... 

There are examples for RStudio, VSCode, PostgresSQL, but no generic SQL client. 

Best,

Etienne

**Comment by rickbergfalk** [comment]
I don't have too much time these days but I'd be open to accepting a PR if someone worked on this!
