### ISSUE TITLE
Cannot SignUp

### ISSUE THREAD

**Issue by WGcode400** [sqlpad/sqlpad#1117]
Getting a forbidden message on the latest docker build when trying to create a new user

**Comment by shawncao** [comment]
have the same issue.

**Comment by rickbergfalk** [comment]
Which auth are you using? I just tried latest and was able to set it up just fine. I was able to log in with local auth, add a user, and sign up with that user, with env vars

```
SQLPAD_ADMIN: 'admin@sqlpad.com'
SQLPAD_ADMIN_PASSWORD: 'admin'
```

**Comment by WGcode400** [comment]
i just tried to login with that user and password and it said username or password is incorrect, what do you mean which auth? I just pulled the latest from docker, and running it on localhost :3000

**Comment by WGcode400** [comment]
just tried creating a login again and still forbidden

**Comment by WGcode400** [comment]
![image](https://user-images.githubusercontent.com/92390104/160438215-f7ce2277-9648-48bd-bf14-8ccd69342d6a.png)

**Comment by WGcode400** [comment]
![image](https://user-images.githubusercontent.com/92390104/160438380-863df678-bd8d-4f2d-bf68-e0d75f57d765.png)

**Comment by WGcode400** [comment]
![image](https://user-images.githubusercontent.com/92390104/160438660-1a3857e5-4b26-42c1-bd71-59b31beb9860.png)

**Comment by WGcode400** [comment]
![image](https://user-images.githubusercontent.com/92390104/160438952-fa231c80-3201-4dd2-9542-8dc779ace581.png)

**Comment by rickbergfalk** [comment]
Hi @WGcode400. By which auth I meant what authentication method do you have configured? https://getsqlpad.com/#/authentication

If you are using local/basic authentication (the traditional username and password) you must first set the initial admin credentials using environment variables.

**Comment by WGcode400** [comment]
this fixed it thanks @rickbergfalk
