### ISSUE TITLE
can I update all dependencies  in client and server package.json and replace the npm with yarn?

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#1120]
Hi, @rickbergfalk @eladeyal-intel 
Can I bump all dependencies  in client `package.json` and server `package.json` to latest version
and replace the `npm` with `yarn`? 

If I can, what matters need attention when I upgrade the versions.

I use the `yarn` faster than `npm`.

**Comment by eladeyal-intel** [comment]
I have no feedback

**Comment by rickbergfalk** [comment]
I'd be okay with `yarn`. I've been hesitant to adopt latest npm after having some issues with peer dependencies the last time I tried it. I'd also be okay with moving to `pnpm` as well, which is also supposed to be an improvement.

As for bumping all dependencies - there are some that we cannot bump to latest. I'm trying to keep them documented here https://github.com/sqlpad/sqlpad/blob/master/DEPENDENCIES.md.

Whenever I bump dependencies I try to do a quick general regression test via the UI for core functionality, but some of the stuff like auth is difficult to test if there aren't test cases set up. If we spend some time writing tests or manually testing those hard-to-test dependencies, I'd be more than okay moving them to latest :)

**Comment by rickbergfalk** [comment]
@dengc367 I was going to test to see how pnpm works. If it is faster than yarn are you open to pnpm?

**Comment by dengc367** [comment]
OK. Great. @rickbergfalk

**Comment by rickbergfalk** [comment]
@dengc367 I gave pnpm a shot. For me it was a bit faster, but I'm missing the package upgrade utilities from npm and yarn... so I say we go with yarn!

Will have a PR shortly

**Comment by rickbergfalk** [comment]
Yarn PR has merged
