### ISSUE TITLE
Why route listConnections did not remove password 

### ISSUE THREAD

**Issue by dee-el** [sqlpad/sqlpad#1121]
As per title, I see the password field is still filled on `listConnections` response

https://github.com/sqlpad/sqlpad/blob/bf51d19e8b7f15a8a721cfe9d411e1d7b33ce009/server/routes/connections.js#L22-L39

Since all routes on `connections` already did remove the password value from response, is this intended or miss ?

**Comment by rickbergfalk** [comment]
🙀 Thanks for catching this @dee-el! I think it was just missed and no one noticed since it is not displayed in UI

**Comment by sapisuper** [comment]
Hi guys, I just create quick fixing with remove sensitive data like username, password and host in listConnections. please check this changes.

https://github.com/sapisuper/sqlpad/commit/6025e79f901dda8184ceddd8361e1617d43698a5

**Comment by dee-el** [comment]
> Hi guys, I just create quick fixing with remove sensitive data like username, password and host in listConnections. please check this changes.
> 
> [sapisuper@6025e79](https://github.com/sapisuper/sqlpad/commit/6025e79f901dda8184ceddd8361e1617d43698a5)

Hi, @sapisuper

I have a question and a suggestion
If you remove those data directly from `models/connections.js`, what happen if there are any module(s) need those data (even if I doubt there will be that) ?

I suggest to rename function `removePassword`, it is confusing since what it actually does is removing sensitive credentials not just password anymore

If those two can be applied, I think it is good to be PR.
What do you think @rickbergfalk ?
