### ISSUE TITLE
support multiple sqleditor tabs

### ISSUE THREAD

**Issue by wangqinghuan** [sqlpad/sqlpad#1123]
It's not convenient  support only one code editor.
Could we build a multi-tab code editor like common IDE?
![image](https://user-images.githubusercontent.com/22762150/166500224-054c4355-0b46-46d1-b151-76a2385a1281.png)

**Comment by rickbergfalk** [comment]
This was something I planned for, but unsure if I'll have time for it. If anyone looks into this on frontend, the zustand state is organized for multiple tabs, the display components and URLs just need to be figured out.

**Comment by eladeyal-intel** [comment]
I actually like to simplicity of the interface. Hopefully, multiple tabs is opt-out.
