### ISSUE TITLE
Certificate error connecting to SQL Server with encryption

### ISSUE THREAD

**Issue by davidcomerford** [sqlpad/sqlpad#1165]
Hi,

I'm trying to connect to an AWS RDS SQL Server instance and getting following error:
_Failed to connect to dbname.eu-west-1.rds.amazonaws.com:1433 - unable to get local issuer certificate_

Works fine no encryption but that's not an option for me.

SQLPad: 6.11.2
Node: v14.21.1

**Comment by nilijev** [comment]
I have the same issue trying to connect to SQLServer cluster from SQLPAD container. It forces to check 
_"Encrypt (necessary for Azure)"_ with message _"Server requires encryption, set 'encrypt' config option to true."_

With option checked, the error is: 
_"Failed to connect to <DBSERVER>:1433 - unable to get local issuer certificate"_
I tested connection

**Comment by nilijev** [comment]
I have checked connectivity to SQL Server using sqlcmd utility and I've got the same error. By adding -C switch (Trust Server Certificate) to sqlcmd, the connection worked. The question is - how to add that to SQLPAD connection?

**Comment by davidcomerford** [comment]
So I was working with AWS RDS specifically so what I did was feed the AWS RDS SSL cert bundle into Node's environment inside my sqlpad systemd unit file.

Bundles for each region: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

```
[Service]
Type=simple
ExecStart=/opt/sqlpad/server/server.js --config /opt/sqlpad/server/config.test.env
Restart=always
User=sqlpad
Group=sqlpad
Environment="NODE_EXTRA_CA_CERTS=/opt/sqlpad/eu-west-1-bundle.pem"
Environment=PATH=/usr/bin:/usr/local/bin
WorkingDirectory=/opt/sqlpad/server
```

**Comment by nilijev** [comment]
is there a way to add checkbox for "Trust Server Certificates" which will set  ssl configuration for SQL Server  trustServerCertificate
(I think it should be on the same place where Encrypt: is set)

**Comment by nilijev** [comment]
I suppose it should be added here:

    options: {
      appName: 'SQLPad',
      encrypt: Boolean(connection.sqlserverEncrypt),
      multiSubnetFailover: connection.sqlserverMultiSubnetFailover,
      readOnlyIntent: connection.readOnlyIntent,
      // Set enableArithAbort to avoid following log message:
      // tedious deprecated The default value for `config.options.enableArithAbort`
      // will change from `false` to `true` in the next major version of `tedious`.
      // Set the value to `true` or `false` explicitly to silence this message. ../../node_modules/mssql/lib/tedious/connection-pool.js:61:23
      enableArithAbort: true,
      // ADD  trust certificate option - either hardcoded or linked to checkbox
      trustServerCertificate: true
    },

**Comment by davidcomerford** [comment]
Dare you to add it and create a PR :smile:

**Comment by nilijev** [comment]
We solved issue by using configmap to replace original index.js form sqlserver driver with one containing  trustServerCertificate: true.
Still, would be nice to have checkbox for MS SQL Server to control this option.
