### ISSUE TITLE
Columns with equal names don't get shown in the output

### ISSUE THREAD

**Issue by marcel-gohsen** [sqlpad/sqlpad#1167]
![image](https://user-images.githubusercontent.com/29226023/204547836-2b7504f9-ca50-497d-b944-67a6bfba07ed.png)

The above query should return the Cartesian product of the table "Mitarbeiter" with 10 columns. 
Instead, only 5 columns are there. It looks like columns with the same column name get dropped.

I'm on SQLPad Version 6.11.3.

**Comment by rickbergfalk** [comment]
Hi @marcel-gohsen - this is a known limitation. This won't be addressed unfortunately as the project is in maintenance mode and isn't seeing any new development.
