### ISSUE TITLE
Docker Images after 6.11.2 missing ARM64 build

### ISSUE THREAD

**Issue by jjschwarz** [sqlpad/sqlpad#1173]
The docker images up to 6.11.2 included both AMD64 and ARM64 builds.  After that version the docker images appear to only include AMD64 binaries.  Would it be possible to get the ARM64 image included in the build again, as we run SQLPad on an ARM64 platform (Raspberry Pi 4).

Thank you

**Comment by rickbergfalk** [comment]
Sorry about that! Lost them with the switch to having docker hub build. Will try to have them back for the next version.

**Comment by jjschwarz** [comment]
Thank you!  I will keep an eye out for them before we upgrade my install next.
