### ISSUE TITLE
Add customizable toolbar and app header

### ISSUE THREAD

**Issue by rickbergfalk** [sqlpad/sqlpad#528]
I've received a request to allow customizing the "toolbar" (re-arranging and removing elements from it) as well as adding the ability to add an application header above the toolbar, similar to how the UI prior to v3 was. The application header would also have some amount of customization allowed as well.

This is primarily for organizations embedding SQLPad into other applications or portals.

Is this something others would find useful?

My initial thought on the approach would be to take the existing toolbar and break it out into smaller components, and initialize it with some config string. For example the following string would have the queries button on the left, schema button and connection selector centered, and menu button on the right: 

```
SQLPAD_TOOLBAR="[queries_button] [spacer] [schema_button] [connection_selector] [spacer] [menu_button]"
```

For the application header this would be a bit more difficult, as you'd presumably want to customize the content (change title for example) and it'd be less interactive. This ends up looking kinda like JSX, but JSX isn't something that can easily be integrated after initial build of the SQLPad UI. 

```sh
# this looks like JSX but not, and its not something I'd like to parse and implement
SQLPAD_APP_HEADER="[spacer] [app_title title='My company's SQLPad'] [spacer] [user_name]"
# maybe it should be a mustache/handlebars template instead?
SQLPAD_APP_HEADER="<div id='app-header'><h1>My company's SQLPad</h1><div class='spacer' /><div>{{user.name}}</div>"
```

Alternatively, instead of having this something injected by config, efforts could be made to make it easier to provide these customizations in a fork and minimize conflict?

**Comment by activiz** [comment]
Hi @rickbergfalk, I would like to see this as a feature.

**Comment by eladeyal-intel** [comment]
Here's a simple suggestion (I think). Add two configuration items:

1. `SQLPAD_HTML_PROLOGUE`

    Any HTML code provided here will be injected at the top of the SQL page (inside div id="root"). It can be used for branding, A simple example:

```html
<div style="padding: 4px; color: black; background-color: #CCFFFF">Your content goes here</div>
```

2. `SQLPAD_HIDE_HEADER`

    If set to true, the header will not be displayed. SQLPad branding will be provided elsewhere.

So setting these two example together, you'll get something like this:

![image](https://user-images.githubusercontent.com/20379005/84077631-53af7e80-a9e0-11ea-8f7b-f735b66042be.png)

**Comment by rickbergfalk** [comment]
@eladeyal-intel is this a feature you're interested in as well? 

I did something like that first part in a PR but held off merging. https://github.com/rickbergfalk/sqlpad/pull/549

That PR did end up going into a fork of SQLPad I'm maintaining, but the custom header work is eventually going to be replaced with a custom front-end. Setting the HTML via config, then sending it via server turned out to be too limited.

Alternatives were brought up such as following some sort of plugin model and have that put in the UI project to allow for more flexibility. 

As things stand I'm not sure how widely used this would be, and what common use cases would be for it.

**Comment by rickbergfalk** [comment]
@activiz are you interested in the reordering of the buttons and inputs displayed in the toolbar/header or are you looking to add custom content like a logo? or both?

**Comment by eladeyal-intel** [comment]
If there was an easy way to customise without needs of additional seveI would have used it.

**Comment by rickbergfalk** [comment]
Going to close this one out. This work was originally scoped for a custom SQLPad fork I was working on, and the customization didn't really pan out. Technically it worked, but it wasn't flexible enough.

Not sure to what customizations would be of interest to others, but I'm concerned it is something that could gradually snowball into something difficult to maintain or lots of different config... and I find myself with less and less time these days
