### ISSUE TITLE
Handle multiple result sets

### ISSUE THREAD

**Issue by rickbergfalk** [sqlpad/sqlpad#531]
I'd like to improve SQLPad's handling of multiple result sets. What this looks like I'm not sure yet, and may end up having to be database dependent due to driver implementation.

Multiple result sets will be broken out and rendered into multiple grids. For the initial implementation, data visualization will likely be disabled when multiple results are returned (or at least limited to 1 result set)

**Comment by dengc367** [comment]
Regardless of any connection,  multi queries separated by semicolon need to be supported. Despite some drivers (eg: mysql, allowMultiQueries=true) can native support.

**Comment by rickbergfalk** [comment]
@dengc367 the server side of things is handled for this by the [sql-limiter](https://github.com/sqlpad/sql-limiter) library. 

Regardless of driver, sqlpad will split queries on `;` and run them separately (reusing the same database connection if possible). 

What's left is to work on the UI to render these a separate queries. Right now the last query run is displayed

**Comment by eladeyal-intel** [comment]
Maybe we can change the GUI to be more "flowing", so when a query is "RUN" its output will be displayed at the bottom

 ![image](https://user-images.githubusercontent.com/20379005/92601381-670b0800-f2b5-11ea-9439-34f0868f2113.png)

similar to Jupyter Notebooks except that you can't edit the past, only add at the bottom. This way is more similiar to  CLIs (terminal) in the sense that user can look back to what s/he did and see previous error messages etc.

**Comment by rickbergfalk** [comment]
@eladeyal-intel if the flowing format were used, would you see an issue if the table was paginated and fixed to displaying a small number of rows at a time (like 10 or so)? I'm thinking it would be necessary to prevent having a scrollable area inside another scrollable area, which can become tricky to navigate. Maybe the smaller table could be expanded to full screen if a full scrollable table was desired?

If this was implemented, I'd  personally want it to be an option for end user to switch between the 2 layouts. 

When I write SQL I tend to iterate without much need for history, and its kind of nice to have everything fixed in place.

Regardless of layout, I still need to figure out how charting is going to work with this...

**Comment by dengc367** [comment]
I think the `TAB` format above the result region is good for habit, like multi-queries scenario in Navicat software.

**Comment by rickbergfalk** [comment]
Update on this - multiple result set support is implemented in v6 branch but not with the flowing UI. 

I think its worth exploring this alternative display though, so I'm going to leave this issue open and target a 6.x release.

**Comment by rickbergfalk** [comment]
Tried experimenting with a flowing UI and I'm not so sure its a good fit. A lot of little nuances of interaction became kind of tricky to deal with and impacted some of the existing flows today (do you focus on next editor? what happens if query results fill page?). These UI interactions are solved when on the CLI, but started to feel clunky on the web.

Another challenge stems from having to "virtualize" the blocks of information, as the gradual addition of components from prior runs starts to take a toll on React perf without special handling.

Instead I leveraged the flowing layout somewhat and added a history button, which opens the history for the current query. Each entry can be loaded back into editor state, including chart configuration, which is kind of neat. 


![sqlpad-history-button](https://user-images.githubusercontent.com/303966/111413533-69a74980-86ac-11eb-9f8f-694b2ae080c9.jpg)

![sqlpad-history-open](https://user-images.githubusercontent.com/303966/111413534-6a3fe000-86ac-11eb-97f8-d756118c5803.jpg)


Limitation to current implementation however is that query results are not shown. This is partially a restriction on front end data limits, as well as a consequence of how the query result data is stored. Each query result is stored as a JSON blob, so there's no efficient way to take a small subset from each without reading the whole thing.

Enhancing the history previews will require some minor enhancements to the way query data is being stored today, but I'm not sure how strong the need is for that.
