### ISSUE TITLE
Showing MySQL functions & stored procedures in the schema sidebar

### ISSUE THREAD

**Issue by HardNo** [sqlpad/sqlpad#564]
I'm looking to use SQLPad as an alternative to MySQLWorkbench. 

Currently, the mysql driver only pulls back tables & views from the information_schema.tables. However, MySQLWorkbench also shows stored procedures and functions (from information_schema.routines).

Any thoughts on enhancing this driver?

**Comment by rickbergfalk** [comment]
Hi @HardNo! No official plans to do this but I'm not opposed. 

Functions and stored procedures are not pulled for any of the other databases so I think some investigation would be needed as to how to format this data so it is flexible but useful.

**Comment by rickbergfalk** [comment]
Going to close this one out. I'm still not opposed if someone wants to work on adding this, but I know it would be difficult given current implementation, and is something I won't have time to work on.
