### ISSUE TITLE
Add metadata description fields for schemas and tables

### ISSUE THREAD

**Issue by murphyke** [sqlpad/sqlpad#630]
Currently, descriptions can be supplied for table columns, but for complicated data, it would be helpful to support descriptions for tables and schemas as well.

I'm going to describe the current state of the relevant data structures and functions and then make a proposal for a possible solution.

#### Current situation

1. A database driver prepares metadata in this flattened structure:

   ```json
   {
     "rows": [
       {
         "table_schema": "schema-name",
         "table_name": "table-name",
         "column_name": "column-name",
         "data_type": "column-data-type",
         "column_description": "column description"
       }
     ]
   }
   ```

2. The driver then invokes [formatSchemaQueryResults](https://github.com/rickbergfalk/sqlpad/blob/224f1807f149de0b8d6707950e897302f75d879b/server/drivers/utils.js) (a utility function supplied by `server/drivers`) to convert the metadata into the following format:

   ```json
   {
     "schema-name": {
       "table-name": [
         {
           "table_schema": "schema-name",
           "table_name": "table-name",
           "column_name": "the column name",
           "data_type": "string",
           "column_description": "an optional description"
         }
       ]
     }
   }
   ```

   (I believe the `table_*` fields may be subsequently ignored, since they are redundant.)

   This is the final version of the metadata as far as the driver is concerned; the driver returns it to SQLPad.

3. In [client/src/schema/SchemaSidebar](https://github.com/rickbergfalk/sqlpad/blob/224f1807f149de0b8d6707950e897302f75d879b/client/src/schema/SchemaSidebar.js), a call is made to [getSchemaList](https://github.com/rickbergfalk/sqlpad/blob/224f1807f149de0b8d6707950e897302f75d879b/client/src/schema/getSchemaList.js), which converts the metadata to a new format which is tailored to displaying the metadata tree in the sidebar.

   That format is a list of every node in the tree (whether schema, table, or column) and looks like this:

   ```json
   [
     {
       "type": "schema",
       "name": "test",
       "id": "test",
       "parentIds": []
     },
     {
       "type": "table",
       "name": "dogs",
       "schemaName": "test",
       "id": "test.dogs",
       "parentIds": ["test"]
     },
     {
       "type": "column",
       "name": "name",
       "dataType": "STRING",
       "tableName": "dogs",
       "schemaName": "test",
       "id": "test.dogs.name",
       "parentIds": ["test", "test.dogs"]
     }
   ]
   ```

#### Proposed change

1. Database drivers could remain unchanged, but if they wanted to add schema and/or table descriptions, they could just add fields for those in the data structure that they currently pass to `formatSchemaQueryResults`, e.g.:

   ```json
   {
     "rows": [
       {
         "table_schema": "schema-name",
         "table_schema_description": "schema description",
         "table_name": "table-name",
         "table_description": "table description",
         "column_name": "column-name",
         "data_type": "column-data-type",
         "column_description": "column description"
       }
     ]
   }
   ```

    A little wasteful, but bearable?

1. `formatSchemaQueryResults` could be modified to return a more general data structure:

   ```json
   {
     "schemas": [
       {
         "name": "schema-name",
         "description": "the schema description",
         "tables": [
           {
             "name": "table-name",
             "description": "the table description",
             "columns": [
               {
                 "name": "the column name",
                 "data_type": "string",
                 "description": "an optional description"
               }
             ]
           }
         ]
       }
     ]
   }
   ```

   Depending on taste, this structure could also be simplified to just be a list of schemas instead of being an object with a `schemas` field containing the list of schemas.

1. [searchSchemaInfo](https://github.com/rickbergfalk/sqlpad/blob/224f1807f149de0b8d6707950e897302f75d879b/client/src/schema/searchSchemaInfo.js) would be modified to understand the new data structure. (This function filters the data structure to remove tables that don't match a search expression).

1. [getSchemaList](https://github.com/rickbergfalk/sqlpad/blob/224f1807f149de0b8d6707950e897302f75d879b/client/src/schema/getSchemaList.js) would be modified to understand the new data structure and include the new schema and table description fields.

1. [SchemaSidebar](https://github.com/rickbergfalk/sqlpad/blob/224f1807f149de0b8d6707950e897302f75d879b/client/src/schema/SchemaSidebar.js) would be modified to display the schema and table description strings in the same way that the column descriptions are currently being displayed.

1. (Added by Rick) [client/src/utilities/updateCompletions.js](https://github.com/rickbergfalk/sqlpad/blob/master/client/src/utilities/updateCompletions.js) needs to be updated so the auto-completion logic understands the new data structure.

@rickbergfalk If this solution seems good to you, I could submit a PR. I would also like to add in the use of `title` tooltips for the description text, to make it easier for users to see long descriptions.

A variation on the above would be to change all the drivers to not use the intermediate data structure that is passed to `formatSchemaQueryResults` and have them return the "formatted" structure directly, with the result that `formatSchemaQueryResults` could be eliminated. My natural laziness slightly biases me against this option.

Another change that I would be tempted to make would be to have the search feature match against the descriptions as well as the names, but that could be in a subsequent PR if you want.

**Comment by rickbergfalk** [comment]
I'm all for these changes! Some thoughts off the top of my head

> Depending on taste, this structure could also be simplified to just be a list of schemas instead of being an object with a schemas field containing the list of schemas.

I'm in support of changing this API to be a list of schemas instead of a top level object, unless there is some top-level information we would also want to include (like the date the schema was last pulled or something, but I don't think that is necessary)

Another component that might need to be updated is the autocomplete functionality. I don't recall the format it uses offhand but I think it operates on the existing schema structure.

> My natural laziness slightly biases me against this option.

Same! 😂 

I'm also okay if that helper function is used for an initial generic lazy solution, and drivers that want to optimize to produce the proper format outright may do so.

**Comment by murphyke** [comment]
> I'm all for these changes!

OK, thanks for your helpful comments. I added auto-completion to the TODO list above. We'll schedule this work soon.

**Comment by rickbergfalk** [comment]
@murphyke I don't know if you have started this at all, but I've run into a scenario supporting Apache Pinot where I need to make schema optional. 

I'm going to start implementing the 2nd format for the flexibility.

**Comment by rickbergfalk** [comment]
Just realized that this would be considered a "breaking" API change, and I'm not quite ready to do that. There isn't really a pattern set up for versioned APIs either.

I think what I'm going to do is create 2nd API under the route `/api/connections/<connectionId>/schema` which will serve as the eventual replacement of `/api/schema-info/<connectionId>`. 

The UI will switch to using the new route, and eventually the old route will be removed.

**Comment by rickbergfalk** [comment]
Forgot to close this one out once it was implemented. `GET /api/connections/<connectionId>/schema` will return something that looks like the following. Not all databases will have description info for everything - it is up to drivers to provide that info. If it exists it'll be shown.

```json
{
  "schemas": [
    {
      "name": "schema_1_name",
      "description": "",
      "tables": [
        {
          "name": "table_1_name",
          "description": "",
          "columns": [
            {
              "name": "column_1_name",
              "description": "",
              "dataType": "INT"
            },
            {
              "name": "column_2_name",
              "description": "",
              "dataType": "TEXT"
            }
          ]
        }
      ]
    }
  ]
}
```
