### ISSUE TITLE
Long string from resultset UX

### ISSUE THREAD

**Issue by hannsdirkbrinkmann** [sqlpad/sqlpad#661]
My query returns a quite long nvarchar that I need to copy and paste somewhere. I did not manage to copy the query result into the clipboard - am I missing something?

![image](https://user-images.githubusercontent.com/64576833/83732446-5579ea80-a64c-11ea-85b7-7175994595dc.png)

**Comment by rickbergfalk** [comment]
Hi @hannsdirkbrinkmann 

This is something that can be improved. Right now depending on your browser/os, if you double-click all the text to highlight and press your copy shortcut, you should get all the text copied to clipboard even though you can't see it.

Introducing some sort of context menu might be of interest here though. We can leave this issue open and address this need in some way.

**Comment by dop251** [comment]
I've run into the same issue. How about maybe enable horizontal scroll in the cell?

Otherwise it really is a great tool. I was surprised how difficult it was to find something lightweight and free, nice job!

**Comment by rickbergfalk** [comment]
Thanks @dop251! 

Would a right-click copy context menu solve your need? horizontal scroll within a scrollable container could get tricky. I'm about to work on adding a context menu to copy cell content similar to menu used on the schema sidebar.

**Comment by dop251** [comment]
In my case I just want to see the value. If scrolling is tricky maybe add a tooltip?

**Comment by rickbergfalk** [comment]
@dop251 Some values could get long for a tooltip too. A database I frequently test with is SQLPad's own database, and the query history view has the entire SQL text that was run for example. 

What if there was an option to view row data in a dialog/modal window that could scroll  if necessary?

Not as convenient as a tooltip, but the results could be viewed, selected, scrolled as desired.

**Comment by dop251** [comment]
That would work. I just need any way of seeing the entire value without leaving the UI.

**Comment by rickbergfalk** [comment]
@dop251 check out release 6.4.0. Right-clicking a result cell will have an option to expand cell value, which will open it in a modal. Should allow you to see the whole value and scroll if necessary.

**Comment by dop251** [comment]
Works nicely, thanks! The only thing I've noticed is it doesn't look right in the History view: the right-click menu is misplaced and clicking on 'view expanded value' results in an empty popup. It doesn't bother me though, just something to tidy up maybe.

**Comment by rickbergfalk** [comment]
@dop251 I see there's some extra whitespace that needed fixing, but otherwise things are showing for me on Windows 10 using Chrome.

Which OS and browser are you using?

![sqlpad-history-context](https://user-images.githubusercontent.com/303966/111019438-db1d8a00-8384-11eb-9d9a-97467683c1c9.jpg)
![sqlpad-history-modal](https://user-images.githubusercontent.com/303966/111019439-db1d8a00-8384-11eb-900b-a1676e11bc46.jpg)

**Comment by dop251** [comment]
Looks like it was a cache issue, shift-refresh has fixed it, sorry.

**Comment by rickbergfalk** [comment]
No worries! Glad its fixed!
