### ISSUE TITLE
"Configure visualization" modal should be draggable

### ISSUE THREAD

**Issue by eladeyal-intel** [sqlpad/sqlpad#741]
The "Configure visualization" modal window should be draggable (movable) so that one could inspect the changes in the graph behind it.

**Comment by rickbergfalk** [comment]
What do you think about it being a toggled sidebar similar to schema? I was thinking it could either go on the right hand side, or replace schema sidebar potentially?

**Comment by eladeyal-intel** [comment]
I thought adding a "draggable" decoration would be super easy for one versed in js. 

I'm not sure it's a good idea to put the graphs on the far right and their controlled  on the far left.

**Comment by rickbergfalk** [comment]
Yeah I was thinking the same.

Dragging is possible but I haven't really liked the modal in general. It was kind of a quick and easy solution to removing the previous tabbed design.

Another thing I'm trying to think about and solve is managing query name, tags, sharing, potentially adding description?

Adding a general sidebar that could act as a space for these things might be nice and flexible? Kind of a properties sidebar of sorts.

**Comment by eladeyal-intel** [comment]
In my opinion, the schema window should be of higher priority than other property panels. In my experience it is always visible.  it can be hidden if you are out of screen Real estate. But otherwise it is always visible. It is the same priority and class as the query window and the results window. So that's why I don't think it is interchangeable with the connections list or the visualization configuration.
