### ISSUE TITLE
configuration about showing column comment in result area  

### ISSUE THREAD

**Issue by WolfeeLuo** [sqlpad/sqlpad#789]
I want to know if there is any configuration to let result area show the column comment.
The background is that some members in my team are not developer and they're not so familiar with the meaning of every columns.
So if the column comment can be shown along with the result, they can understand the result better and fast.
Actually, another tool PHPMYADMIN has this feature. 
We has just migrated to sqlpad from PHPMYADMIN, and that's why they always complain about this......

**Comment by rickbergfalk** [comment]
There is not. I think the comment could be added to the schema sidebar, but adding to the results would be tricky as the results are from arbitrary SQL statements, not necessarily bound to a particular table.
