### ISSUE TITLE
Changing queries uses same underlying connection (potential UX issue)

### ISSUE THREAD

**Issue by rickbergfalk** [sqlpad/sqlpad#806]
This only applies when **multi-statement transaction** mode is enabled for a connection.

When multi-statement transactions are enabled, an underlying database connection is kept open and reused across query runs. 

If a query that takes a long time to run is executed, then a new query is opened and executed, query 2 will not finish until query 1 does. 

For example, to reproduce this with a Postgres connection with multi-statement transaction enabled, save the following 2 queries, execute the long query, then switch to short query and immediately execute. Note that the short query should return immediately, but will wait roughly 30 seconds prior to returning.

```sql
SELECT 'long query' AS name FROM pg_sleep(30);
```

```sql
SELECT 'short query' AS name;
```

This is potentially misleading, as you wouldn't think what was executed under a previous saved query applies to the current query.

I'm not entirely sure how to go about solving this other than to open a new database connection for each saved query?

**Comment by eladeyal-intel** [comment]
Does this refer to API or to GUI?

For GUI : the only way to "switch to short query" is to actively cancel the long query (I.e. Pressing f5) so I (as a user) would imagine everything behind the dismissed query (including transaction state) is lost.

**Comment by rickbergfalk** [comment]
Only the UI... Though ideally API would support the ability to cancel queries too. The majority of node db drivers don't support this though, so instead of cancelling, the query results need to be ignored.

**Comment by eladeyal-intel** [comment]
So the GUI client can send uuid which would catch the case that the user dismissed the request; and the server could use that to start a new transaction.

In other words it means the GUI communicates via the API an id for the connection.

**Comment by rickbergfalk** [comment]
This is fixed in v6 branch. I was overthinking the problem. If a SQLPad setup/user is using persistent connections using multi-statement transaction mode, and they load a new query, the database connection is closed and reopened to ensure a fresh connection.
