### ISSUE TITLE
After creating a query, can i call the query with parameters as a rest api?

### ISSUE THREAD

**Issue by hkjang** [sqlpad/sqlpad#819]
First of all, thank you for making a good product.

This is a question about your product features. 
After creating a query, can i call the query with parameters as a rest api?

**Comment by rickbergfalk** [comment]
Thanks @hkjang! There is an API you can use to get and run queries, but nothing that supports parameters currently. 

There's nothing restricting the actual SQL used when executing the SQL from the saved query, so you could use your own placeholders, perform a GET on the query to get the SQL text, replace those placeholder values with something else, then POST a new query batch with the new SQL text.

Parameters would be more ideal however
