### ISSUE TITLE
connections error

### ISSUE THREAD

**Issue by zhangzw001** [sqlpad/sqlpad#840]
connections error: 

{"level":50,"time":"2020-09-21T03:38:00.366Z","pid":1,"hostname":"sqlpad","name":"sqlpad-app","stack":"SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at /usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:183:72\n    at Array.map (<anonymous>)\n    at Query.handleJsonSelectQuery (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:182:21)\n    at Query.formatResults (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:127:12)\n    at Query.run (/usr/app/node_modules/sequelize/lib/dialects/mariadb/query.js:72:17)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /usr/app/node_modules/sequelize/lib/sequelize.js:619:16\n    at async MySQLQueryInterface.select (/usr/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:938:12)\n    at async Function.findAll (/usr/app/node_modules/sequelize/lib/model.js:1741:21)\n    at async Function.findOne (/usr/app/node_modules/sequelize/lib/model.js:1905:12)\n    at async SchemaInfo.getSchemaInfo (/usr/app/models/schema-info.js:18:17)\n    at async getSchemaInfo (/usr/app/routes/schema-info.js:25:20)","type":"Error","msg":"Unexpected token o in JSON at position 1"}

env:
      SQLPAD_BACKEND_DB_URI: 'mariadb://sqlpad:xxx@xxx:3306/sqlpad'
      SQLPAD_SESSION_STORE: 'database'

version:
    sqlpad images : sqlpad/sqlpad:5.6.0
   mariadb: 10.5.5

thanks~

**Comment by rickbergfalk** [comment]
Thanks for the info @zhangzw001. Will have to see if this can be reproduced.

Is the connection you are getting the schema for also in mariadb?

**Comment by rickbergfalk** [comment]
I'm unable to reproduce this. I've added a mariadb example in the docker examples directory at https://github.com/rickbergfalk/sqlpad/tree/master/docker-examples/mariadb. 

@zhangzw001 if you could get more info or reproduce the issue using docker-compose that'd be great.
