### ISSUE TITLE
get table name (fully qualified) from schema sidebar to code window

### ISSUE THREAD

**Issue by baikal** [sqlpad/sqlpad#849]
Hi
Is there a way to get a SCHEMA.TABLE name from the schema sidebar into to code window? Like drag and drop or some magic ctrl-click on the table name in the schema sidebar?
If not, as that a possible enhancement to the tool? Which is already really great, thanks!

**Comment by rickbergfalk** [comment]
Thanks Baikal -- There isn't currently. I'd be open to accepting a PR if someone wanted to take a crack at this.

**Comment by baikal** [comment]
I am not exactly a html-gui-framework programmer. Any hints on where to start looking?
I would assume the existing schema/table/column completion selector in the editor is a similar (probably more complex) feature.

or hopefully way simpler as very first step for me: trying to not disable the "able to select text with mouse" feature of the table entry in the schema sidebar, thus allowing to copy paste the string? Some CSS styling?

**Comment by baikal** [comment]
OK, the quick and dirty one was easy: change both 'user-select' CSS-properties from 'none' to 'all' in ./client/src/schema/SchemaSidebar.module.css

This even allows drag-drop of table name (on Chrome at least, one click select all text, then drag) to the text editor. Sorry no PR so far, just a quick hack on my live 5.6.0 installation ...
No 'schema.table' so far, just 'table'

**Comment by rickbergfalk** [comment]
I'll have an experimental version of this in v6 -- see #870 PR for screenshot :)

**Comment by euanmacinnes** [comment]
In the latest build (via Docker) today, the submenu is added, but there is an error in the browser:

Uncaught TypeError: Cannot read property 'writeText' of undefined
    at onSelect (SchemaSidebar.tsx:260)
    at q (index.tsx:406)
    at index.tsx:477
    at index.tsx:715
    at Object.s (react-dom.production.min.js:14)
    at d (react-dom.production.min.js:14)
    at react-dom.production.min.js:14
    at v (react-dom.production.min.js:15)
    at se (react-dom.production.min.js:52)
    at oe (react-dom.production.min.js:51)

in react-dom.production.min.js:52 

and no drag/drop functionality in the browser either (Chrome, latest)

**Comment by rickbergfalk** [comment]
Hmm... Looks like the `writeText` method on the `navigator.clipboard` object is only available when using HTTPS or localhost? https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined. 

drag/drop isn't implemented, and I don't anticipate adding that at all.

I'll have to add a check to see if clipboard is available. If not perhaps a dialog can show encouraging HTTPS.

**Comment by dengc367** [comment]
same problem, it's not available to copy the schema to clipboard.
![image](https://user-images.githubusercontent.com/1353036/100604213-2fa27980-3341-11eb-8c3e-af5c3bf9dcb7.png)

**Comment by baikal** [comment]
first and foremost: thanks @rickbergfalk, this looks amazing.

I stuck with my quickwin of enabling user-select in CSS on 5.6 till yesterday. I tried 6.0 but had the same problem as described by @euanmacinnes / @dengc367 on my real installation (no HTTPS there). Though accessing in from/to localhost works - so at least I can confirm that. And adding the URL to chrome://flags/#unsafely-treat-insecure-origin-as-secure makes it work without HTTPS, too. Though that might not be a good idea securitywise.

**Comment by euanmacinnes** [comment]
Thanks @baikal for the workaround, this is indeed the issue for me, in that it's currently running over HTTP and the HTTPS isn't due to be activated for a while. Adding the URL to the chrome flag got it to work in the meantime.

**Comment by rickbergfalk** [comment]
I'm going to try using an alternate method of writing to clipboard that should hopefully be more supported and not require the security flag change. Work has been merged, so the `latest` docker image should have it once updated.

**Comment by baikal** [comment]
I did check with a recent version from git and can confirm that it now also works over plain HTTP. :+1:

**Comment by rickbergfalk** [comment]
Excellent! Thanks for confirming @baikal

I've tagged a release. This fix is in 6.1.2.
