### ISSUE TITLE
Batch statement results return Forbidden

### ISSUE THREAD

**Issue by jden98** [sqlpad/sqlpad#887]
In the batch processing API, there are at least 4 places in the code where batch.userId is being compared using  !== to user.id.  user.id is an integer, and batch.userId is a string, so 'Forbidden' is always returned.

I hacked in a parseInt on batch.userId, and my API calls are now working.  I'm not sure that's the correct answer, though, so I haven't created a pull request.

**Comment by rickbergfalk** [comment]
Hi @jden98, userId is stored as a string in the backing database (SQLite, Postgres, MySQL, Mariadb, or SQL Server depending on setup)

If using the REST API, try sending your userId as a string like `{ userId: '123' }`.

If this doesn't work let me know...

**Comment by WolfeeLuo** [comment]
> Hi @jden98, userId is stored as a string in the backing database (SQLite, Postgres, MySQL, Mariadb, or SQL Server depending on setup)
> 
> If using the REST API, try sending your userId as a string like `{ userId: '123' }`.
> 
> If this doesn't work let me know...

Hi @rickbergfalk , I got the same issue Now.
Actually your advise doesn't work in my case. just like the following code block in the `bataches.js` under `server/routes` folder which is called when `/api/batches/<batchId>` is called.
```
async function batchToReq(req, res, next) {
  try {
    const { models, user, params } = req;
    const batch = await models.batches.findOneById(params.batchId);

    if (!batch) {
      return res.utils.notFound();
    }

    if (batch.userId !== user.id) {
      return res.utils.forbidden();
    }

    req.batch = batch;
    return next();
  } catch (error) {
    return next(error);
  }
}
```
the `userId` property of `batch.userId` is read from backend database who's type is varchar, while the `id` of `user.id` is the id property of serviceToken object read from database too under the PassportJwtStrategy, but who's type is integer.
