### ISSUE TITLE
User administration 

### ISSUE THREAD

**Issue by nareshgnT** [sqlpad/sqlpad#895]
Is it possible to have editor user but still able to create new connections?

Also it is possible to map the a user to particular connect based based on the login id (dynamically). 

Btw, I love this tool and looking forward to use it. Kudos to the team!!.

**Comment by rickbergfalk** [comment]
Thanks @nareshgnT!

It is not possible at the moment unfortunately. It is something that's been
brought up before though.

Regarding mapping a user to a particular connection, while you can't map a
user to a connection, you can use an experimental feature to map data
attributes of a user to a single connection that has placeholders for those
values. This isn't documented much, and there's no UI to populate user data
values. Getting user data attributes into the database require either using
an auth proxy or doing something via the API/database directly.

https://sqlpad.github.io/sqlpad/#/connection-templates

Another option would require development of a sidecar service of sorts,
that creates connections that are only accessible to a single user using
connection accesses using an API token.

**Comment by nareshgnT** [comment]
Thanks for details, will explore the options

**Comment by nareshgnT** [comment]
@rickbergfalk I switched to auth proxy, but not sure how and where to create connect template.

**Comment by rickbergfalk** [comment]
@nareshgnT a connection template is just a connection. You can use `{{user.data.dbUser}}` anywhere you can define a connection. So you can define the connection with templates via environment variables or in the UI.

I should probably work on an example and put it in docker examples, because it is kind of a confusing concept.
