### ISSUE TITLE
show many lines in result zone when query like `show create table xxxx`

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#902]
when I execute the query like `show create table xxx`, the query result of the table info are squeezed into one line. 
when query result is one line, I suggest the result can recognize the `line-feed`(`return`) character, and can show all information like showing in the Chrome console. 
Is this a good idea? @rickbergfalk 
![image](https://user-images.githubusercontent.com/1353036/99939902-14b29100-2da6-11eb-9f34-1ef3c13038bd.png)

**Comment by rickbergfalk** [comment]
I think this is something worth trying out @dengc367. It might be tricky because of the [react-window](https://github.com/bvaughn/react-window) library in use. It requires a row height to be set for each row, but this can probably be calculated by taking number of lines * line height. 

Another possibility would be to use a regular HTML table for tables  under 100 rows or something, and let the browser grow the row to fit the content. 

Would it be strange if the table used changed implementations based on row count?

I suppose a third option would be to not use the virtualized/windowed table at all and make the table paginated...

**Comment by rickbergfalk** [comment]
@dengc367 I got curious if counting lines would work and it does! Though the truncated text ellipsis goes away (...)

![image](https://user-images.githubusercontent.com/303966/100053912-a215d580-2de6-11eb-9a17-c129b1811d42.png)

If you want to try it out see branch https://github.com/sqlpad/sqlpad/tree/result-row-height

**Comment by rickbergfalk** [comment]
I think we could add an inset shadow/fade on the right-hand side of each cell to fade text out to indicate there is more without using an ellipsis. Text needs to be made darker too.

What do you think about using a monospace font for cell content? I think I like it.

**Comment by dengc367** [comment]
I have tested this great branch [result-row-height](https://github.com/sqlpad/sqlpad/tree/result-row-height), which is just I want. the height is solved, but the max cell width is `350px`, that still hide the content which width is above `350px`.

![image](https://user-images.githubusercontent.com/1353036/100064577-ad601400-2e6d-11eb-9c32-6100eec902df.png)

there is another idea: when click the cell content, the cell is unfolded to display all the content as it is,  like Google Suggestion, but this unfolded cell can scroll vertically and horizontally for the content. this option can affect every cell which in regular table.

monospace font of cell content are nice. I like it too.

**Comment by dengc367** [comment]
or like the github commits, when the content is longer than the cell width and length, the ellipsis will be shown, which can be clicked to unfold the cell in order to display the content as it is.

![image](https://user-images.githubusercontent.com/1353036/100172579-98ce5b00-2f03-11eb-99f8-ad05fc91f19c.png)

**Comment by rickbergfalk** [comment]
I'll see what we can do. For the expand button, it'd require not using a virtualized/windowed library, but that might be okay for small result sets. For single column results we can maybe make the width of the cell 100%.

**Comment by dengc367** [comment]
OK. Yes,  expand button is not supported  in `react-window` now really. 

> I'll see what we can do. For the expand button, it'd require not using a virtualized/windowed library, but that might be okay for small result sets. For single column results we can maybe make the width of the cell 100%.

**Comment by dengc367** [comment]
looking forward to merge this branch to master, haha.

**Comment by rickbergfalk** [comment]
@dengc367 I pushed some updates to result-row-height branch. Want to take a look and try it out? :) 

I'll try using it for a bit to make sure it works with a variety of query results.

![image](https://user-images.githubusercontent.com/303966/100312602-6579e380-2f78-11eb-94eb-6ca956d4c5c3.png)

**Comment by dengc367** [comment]
it doesn't look like yours, only display the first line of the content.
![image](https://user-images.githubusercontent.com/1353036/100338691-e0440c80-3013-11eb-9cea-1b570b860556.png)
![image](https://user-images.githubusercontent.com/1353036/100338761-f81b9080-3013-11eb-862f-92eb4fab1c1d.png)

**Comment by rickbergfalk** [comment]
Oh I think I've figured out what is happening here. Let me see if I can
reproduce.

**Comment by rickbergfalk** [comment]
Ok *now* I think I have this working. It applies to query history too. 

Should a limit be added to height? 

Something I think we could do is if something is larger than some limit, we could render a small button like the GitHub [...] and open the row or cell in a dialog showing full value?

Queries in query history could be quite tall:

![image](https://user-images.githubusercontent.com/303966/100386442-f25d8500-2fea-11eb-888d-bc9a48243adb.png)

JSON values also can get quite tall

![image](https://user-images.githubusercontent.com/303966/100386499-26d14100-2feb-11eb-94be-5f325b1a3c58.png)

**Comment by rickbergfalk** [comment]
Branch is updated if you want to try it out

**Comment by rickbergfalk** [comment]
I tagged 6.0.1 with query history fix. It does not have this work in it. I'll tag that as 6.1.0 but want to see how this feels a bit more before I do

**Comment by dengc367** [comment]
I have tested the branch successfully, fade-out style for the overflow content is a great experience for me. thank you. @rickbergfalk 

![image](https://user-images.githubusercontent.com/1353036/100402782-1e830f80-3098-11eb-894e-574427627aca.png)
![image](https://user-images.githubusercontent.com/1353036/100402810-2d69c200-3098-11eb-9a4c-7215a526d626.png)

**Comment by dengc367** [comment]
> Something I think we could do is if something is larger than some limit, we could render a small button like the GitHub [...] and open the row or cell in a dialog showing full value?

Yeah, the dialog for overflow row is one way.
I think there is another solution for the overflow content for brainstorming: 

 the `B` region on the following screenshot can set up one button like `fold/unfold` to control the result display style, `fold` status is default, if I change  status to `unfold`, the cell is unfold to display the cell content as it is.

![image](https://user-images.githubusercontent.com/1353036/100403975-34de9a80-309b-11eb-8b8d-4cc6057d8798.png)

**Comment by dengc367** [comment]
I consider you can merge the first version/branch to master now, I have tested some scenarios successfully.

**Comment by rickbergfalk** [comment]
fold/unfold is a good idea too 👍 

Will merge shortly and tag as 6.1.0
