### ISSUE TITLE
the catalog can change when using Presto connection

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#904]
Now, we can setup several presto connections for every presto catalog, I need to achieve that :
 I only setup one presto connection with/without default catalog and can change every `catalog` in region `Toggle Schema`, like [yanagishima](https://github.com/yanagishima/yanagishima)
![image](https://user-images.githubusercontent.com/1353036/100202952-f03ced00-2f3c-11eb-9714-d6c7f80ceb22.png)
![image](https://user-images.githubusercontent.com/1353036/100203527-b0c2d080-2f3d-11eb-82aa-e4cbe209eb7a.png)

**Comment by rickbergfalk** [comment]
I think this sort of aligns with similar requests for other databases as well, like SQL Server or MySQL where multiple "databases" can be on a single server and queried against.

I'm not opposed to this, but it could potentially involve a lot of work. I don't know that I have the time but if someone wants to open a PR for it I'd gladly accept. 

@dengc367 something I'm curious about: how would you anticipate saved queries working? Would you expect the query to also save the database/catalog name that is selected?

**Comment by dengc367** [comment]
I think that it need not to save the database/catalog name in the saved queries.

**Comment by dengc367** [comment]
when I have the time, I develop this feature. At first I think whether there will be another good solution.
