### ISSUE TITLE
the row content is hidden by the bottom padding

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#910]
![image](https://user-images.githubusercontent.com/1353036/100530635-596b7b80-322f-11eb-87cc-ec33b9595c92.png)

when I change the [return lines * 22 + 8;](https://github.com/sqlpad/sqlpad/blob/8122d0c945e65c8c9c180d4de760a9199d3bf958/client/src/common/QueryResultDataTable.tsx#L334) to `return lines * 22 + 20;` for padding height,  I have tested successfully in safari and chrome, like the following screenshot.

![image](https://user-images.githubusercontent.com/1353036/100530696-2d9cc580-3230-11eb-86ca-43bd10f2e1bf.png)

**Comment by rickbergfalk** [comment]
Ah bummer I thought I had that figured out. Pushing fix shortly
