### ISSUE TITLE
No access to connections for users with role "editor"

### ISSUE THREAD

**Issue by m50434** [sqlpad/sqlpad#932]
Hi,
im using sqlpad in docker (latest version).

I have set as admin a connection to a MariaDB-Database. For the admin it works: I can access to the database and so on.

I created a further user with the role "editor". I also creates an "access" for this user and for the database. But if I log in with this user, I cannot see any database connections and I cannot choose database connections. 

Even if I create an access "Every Connection" for "everyone" this editor-user cannot see any conenctions.

So what Im doing wrong?

EDIT: 
If I click on "Queries" I can find the connection I set up. So obviously the "chose connection"-field for "editor"-users is missing.

EDIT2:
Admin View:
![grafik](https://user-images.githubusercontent.com/24473301/104039803-1fe74200-51d7-11eb-9627-b33cfe99a045.png)

Editor View:
![grafik](https://user-images.githubusercontent.com/24473301/104039849-355c6c00-51d7-11eb-83e2-a6995bec80ad.png)

**Comment by dgorender** [comment]
Same thing here.

**Comment by rickbergfalk** [comment]
Sorry @dgorender @m50434 just getting to this. For editors the dropdown is not shown if only 1 connection is present.

Does running a query work?

I'll have to see if I can reproduce with a fresh environment. 

I'm thinking that maybe we render something else instead of a dropdown for this instance to inform what database is connected.

**Comment by rickbergfalk** [comment]
Sorry for the confusion with this. In next version there will be a connection name rendered if there is not an option to select a connection, which only occurs if the user is an editor and has access to only 1 connection..

**Comment by eladeyal-intel** [comment]
@rickbergfalk actually we did that intentionally. Why would you display a connection name if there are no options to select from? I think the use case here is that of "personalization" (i.e. different sqlpad instances look the same) which should be handled differently.

If possible I'd prefer the ability to remove the clutter.

**Comment by eladeyal-intel** [comment]
Ref #662

**Comment by rickbergfalk** [comment]
Reopening for discussion...

@eladeyal-intel I remember the hiding was done intentionally, but it didn't occur to me that it might be confusing to the end user. 

Hiding the dropdown might make sense if the SQLPad instance is known to only connect to 1 specific database, but in the event where multiple database connections exist, and the end user only has access to 1 of them, removing the thing that indicates which database they are connected can be confusing.

As you bring up, if there are multiple single-connection instances running, the user needs some indication as to which instance they are connected to.

Any thoughts how this information could be conveyed if not by showing the connection name near the database schema button?

**Comment by eladeyal-intel** [comment]
Ok to close
