### ISSUE TITLE
env var check breaks kubernetes deployments

### ISSUE THREAD

**Issue by mmack** [sqlpad/sqlpad#938]
Hey guys,

just deployed sqlpad in a kubernetes cluster and got this errors:

```
{"level":50,"time":"2021-02-02T17:10:33.372Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_SERVICE_PORT_HTTP\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_SERVICE_HOST\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_PORT\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_SERVICE_PORT\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_PORT_80_TCP_ADDR\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_PORT_80_TCP_PORT\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_PORT_80_TCP_PROTO\" no longer supported."}
{"level":50,"time":"2021-02-02T17:10:33.373Z","pid":1,"hostname":"sqlpad-oracle-6cd765ff7f-hx42p","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Environment variable \"SQLPAD_SERVICE_PORT_80_TCP\" no longer supported."}

```
As i was sure that i was not populating this vars by hand i found this code block:
https://github.com/sqlpad/sqlpad/blob/master/server/lib/config/index.js#L92-L103

This is problematic b/c in K8S for all services that are created in the same namespace they populate some env vars, see:
https://github.com/sqlpad/sqlpad/blob/master/server/lib/config/index.js#L92-L103

And if i name my service sqlpad (which is not too uncommon i think :) ) this whole thing blows up...

Max

**Comment by eladeyal-intel** [comment]
Ref #808 #899

Your analysis seems valid to me. We could except SQLPAD_SERVICE_... but is this just an indication that the concept is wrong? 

Maybe exempt SQLPAD_SERVICE_ and also downgrade the error to warning.

**Comment by mmack** [comment]
Yeah so imho you have two options here:
- either don't raise an error if a SQLPAD_ var is etected - just log it to the console
- Or detect if we're running inside K8S and don't throw anything...

just my 2 cents.

**Comment by eladeyal-intel** [comment]
@mmack #942 should solve for you. I don't have k9s here for testing.

**Comment by rickbergfalk** [comment]
I was wondering if this would eventually be problematic. If the added checks don't work perhaps we log warnings instead of a fatal error.

**Comment by priestjim** [comment]
This conflict exists for `SQLPAD_PORT_` service discovery environment variables as well.
