### ISSUE TITLE
node 15

### ISSUE THREAD

**Issue by eladeyal-intel** [sqlpad/sqlpad#940]
So I'm not really expirienced with this but I was trying to rebuild on WSL2 and it seems to me that the list of supported versions is not totally in order. 

1. I think sqlpad uses https://github.com/mapbox/node-sqlite3 with supportes "Node.js v11.x, v12.x, v13.x and v14.x." (Not v15)

2. https://github.com/sqlpad/sqlpad/blob/master/DEVELOPER-GUIDE.md requries "Node installed at v12.0.0+"  ; Similarly, https://github.com/sqlpad/sqlpad/blob/master/server/package.json has    ` "node": ">=12" `

3. The CI for Release here https://github.com/sqlpad/sqlpad/blob/master/.github/workflows/main.yml only tests `docker://node:13-slim`

4. The CI for tests https://github.com/sqlpad/sqlpad/blob/master/.github/workflows/test.yml only checks ` node-version: [12.x] `

... So I think the v15 is not supported? and not tested?

**Comment by rickbergfalk** [comment]
Not tested, but I'd be surprised that it wouldn't be functional under node 15. It looks like prebuilt binaries are missing for node 15, but does it build if python, gcc, and make are available?

**Comment by eladeyal-intel** [comment]
I was not able to build on wsl2 . I ended up going back to node 12 and installing python2.

That pkg explicitly does not support node 15 so I didn't want to try to hard.

**Comment by eladeyal-intel** [comment]
Huh. Now I see I was having #936 all over again... Same package, same problems.

**Comment by rickbergfalk** [comment]
I haven't tried node 15 out yet personally. I've mostly stuck to LTS releases.

**Comment by rickbergfalk** [comment]
Closing this since we have node 15 in the test matrix and it seems to be working alright
