### ISSUE TITLE
Docker container stopping by itself

### ISSUE THREAD

**Issue by guilhermealmeida1707** [sqlpad/sqlpad#953]
I'm using docker container for sqlpad version 6.2.1 with a Redshift connection and it keeps stopping by itself.
How could I get more information to help to improve this project?

**Comment by eladeyal-intel** [comment]
Docker logs ?

**Comment by rickbergfalk** [comment]
@guilhermealmeida1707 you can try setting `SQLPAD_APP_LOG_LEVEL` to `debug` to log additional information. Could help add some context to what is failing.
