### ISSUE TITLE
xlsx export mis-formats DATE fields

### ISSUE THREAD

**Issue by ianatha** [sqlpad/sqlpad#958]
## What happened?

When running a query that returns DATE values, the UI formats them correctly:
<img width="227" alt="Screen Shot 2021-02-19 at 11 15 59" src="https://user-images.githubusercontent.com/38443/108484175-3be50580-72a4-11eb-968b-4e1eed2c9be2.png">

However, when the query data is exported into `xlsx` the resulting data is in TIMESTAMP format, and not DATE format. I opened the generated `xlsx` file with Microsoft Excel on Windows, Numbers on Mac, and Google Sheets, and they all rendered it the same:
<img width="284" alt="Screen Shot 2021-02-19 at 11 15 38" src="https://user-images.githubusercontent.com/38443/108484074-21129100-72a4-11eb-99f1-c2ed15b0c96c.png">

## What I expected?
I expect the xlsx export to export DATE values in a usable DATE-like Excel format.

### Versions
sqlpad 6.2.1
postgres 12.5

**Comment by ianatha** [comment]
(This is something I'll look into and try to submit a PR.)

**Comment by ianatha** [comment]
Interestingly, running sqlpad (on macOS) locally vs. on EC2 ECS Fargate (Docker) -- connected to the same database -- renders different results, in terms of date formatting!

sqlpad on Docker renders relevant columns as `YYYY-MM-DD`, and the API calls return:
* `/api/batches/UUID`: `{"datatype":"date","max":"2021-02-08T00:00:00.000Z","min":"2018-06-30T00:00:00.000Z","maxValueLength":10,"maxLineLength":10,"name":"billing_date"}`
* `/api/statements/UUID/results`: `[...,"2018-06-30T00:00:00.000Z",...]`

sqlpad on macOS renders relevant columns as `YYYY-MM-DD HH:MM:SS`, and the API calls return:
* `/api/batches/UUID`: `{"datatype": "datetime","max": "2021-02-07T22:00:00.000Z","min": "2018-06-29T21:00:00.000Z","maxValueLength": 23,"maxLineLength": 23,"name": "billing_date"}`
* `/api/statements/UUID/results`: `[...,"2018-06-30T00:00:00.000Z",...]`

Specifically, the `datatype` in `statements.0.columns.0` in `/api/batches/UUID` seems to differ!

🤯

**Comment by ianatha** [comment]
Setting the `TZ` environment variable in Docker causes `api/batches/UUID`'s `statements.0.columns.N.datatype` to be `datetime`, while without `TZ` it is `date`!

This, from [node-postgres.com/features/types](https://node-postgres.com/features/types), seems to be related:

> node-postgres converts DATE and TIMESTAMP columns into the local time of the node process set at process.env.TZ.
> 
> note: I generally use TIMESTAMPTZ when storing dates; otherwise, inserting a time from a process in one timezone and reading it out in a process in another timezone can cause unexpected differences in the time.
> 
>

**Comment by ianatha** [comment]
It's a mix of:
1. postgres transmits DATEs/DATETIMEs/TIMEs/etc as strings
2. `pg` converts the string to a JS Date (which also contains time information) -- this means that when it converts a postgres DATE to a JS Date, it invents the time information (and sets it to midnight UTC)
3. `pg` converts to local timezone using `TZ` env variable (which sometimes makes the end result look like not midnight)
4. `get-columns` in `sqlpad` infers whether or not this is a `Date` or a `Time` on the existence of `T00:00:00` (aka UTC midnight, which may not exist if TZ!=UTC)
5. no typing information is passed to `xlsx`, and a `T` is included between the date and the time portion of a DateTime/Date which breaks Excel's date-parsing

💣 ...

I have a solution in the works.

**Comment by rickbergfalk** [comment]
Thanks for looking into this! Yeah the date/datetime situation is kind of a mess.

I haven't looked into it but I'm guessing CSV export is in a similar situation. The display of datetime fields as dates is something that is done in the UI currently.

**Comment by rickbergfalk** [comment]
@ianatha any progress on this? I can pick this up later this week if you aren't too far into it. 

I'm kind of wondering if this was a regression with the move to the way results are stored. I believe xlsx sheets used to be written with the raw data from the db (dates would be JS date objects) while now the spreadsheet is written on demand, sourcing the data from JSON stored in a database, meaning dates would be strings.

**Comment by rickbergfalk** [comment]
@ianatha I have a fix in place to fix the T and Z display in #976, but I think we can leave this open for further improvement for XLSX export. I don't have Excel, but I don't know if the cleaned up string gets treated as a date or not in the file. I'm guessing it doesn't.

**Comment by ianatha** [comment]
Fixed as of #976
