### ISSUE TITLE
Adding a "do you want to leave" confirmation.

### ISSUE THREAD

**Issue by csimmons0** [sqlpad/sqlpad#963]
Using sqlpad on my macbook, I often accidentally go "back" in the browser and lose the query I was working on. This happens because I'm scrolling leftwards through the query results table on a table with a lot of columns, and scrolling lefttwards too far causes the macbook to think I want to go "back" in the browser. Would it be possible to add one of those "do you want to leave" confirmation popups to stop this from happening?

**Comment by rickbergfalk** [comment]
Definitely! We might need to get creative to target that specific case, but it should be possible. I'll see what I can work up next week.

**Comment by rickbergfalk** [comment]
Just tagged release 6.3.0 that will have this added! Unfortunately there's no way to target the scrolling back scenario that I'm aware of, so instead I'm making the assumption that if the mouse if over the query results, and navigation happens, it wasn't intended.

There are no links in that area, and if there are someday the user can still follow the link by confirming in the prompt.
