### ISSUE TITLE
Support Trino, PrestoSQL ?

### ISSUE THREAD

**Issue by TreeKat71** [sqlpad/sqlpad#970]
Is there any plan to support Trino(previously known as PrestoSQL) ?

**Comment by rickbergfalk** [comment]
Yep! That is on my list of things to do. I think you might still be able to use the existing presto driver, but I'd like to have proper Trino support.

**Comment by TreeKat71** [comment]
That would be nice.
Actually, I used sqlpad with presto driver and it doesn't work.
Trino change everything related to "presto" like header "X-Presto-User" to "X-Trino-User" so I can not get the response.

**Comment by rickbergfalk** [comment]
Oh wow they did. I'll get Trino added quick :)

**Comment by rickbergfalk** [comment]
Just merged Trino support. Docker hub `latest` tag will be updated next 15 minutes or so if you want to give it a try. I'll otherwise probably tag a release later this week.

**Comment by TreeKat71** [comment]
Hi @rickbergfalk ,
There is a bug although it does work fine.
<img width="1263" alt="螢幕快照 2021-03-11 下午5 12 04" src="https://user-images.githubusercontent.com/15715848/110763994-76cbcf00-828d-11eb-8c26-8bb9572424e2.png">
<img width="654" alt="螢幕快照 2021-03-11 下午5 12 17" src="https://user-images.githubusercontent.com/15715848/110763998-77fcfc00-828d-11eb-9e0e-956daa9570f4.png">

**Comment by rickbergfalk** [comment]
Missed something in the copy paste and my test doesn't have as much coverage as I thought. Will fix shortly

**Comment by rickbergfalk** [comment]
Thanks for catching this! Fix is merged and `latest` will be updated shortly.
