### ISSUE TITLE
Postgres json fields shown as [object Object] in csv and xls exports

### ISSUE THREAD

**Issue by dop251** [sqlpad/sqlpad#978]
As per subject. The field shows correctly in the UI.

**Comment by rickbergfalk** [comment]
@dop251 which version of SQLPad are you running? I just merged a fix for this 3 hours ago in #976 .

The fix should be in the `latest` dockerhub image if pulled within the last 2 hours or so.

**Comment by dop251** [comment]
I pulled it today but obviously prior to the fix, can confirm it's working now. Thanks!
