### ISSUE TITLE
when i upgrade to v6.4.2, the errors occured.

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#982]
RT. the following screenshot are the errors: 

![1615777010040](https://user-images.githubusercontent.com/1353036/111098896-62365200-857f-11eb-8368-75924604e02b.jpg)

**Comment by rickbergfalk** [comment]
I think I know went on here. A fix for dev base url is included on prod build. Will have fix shortly.

**Comment by rickbergfalk** [comment]
Tagged 6.4.3. Will take a bit for docker builds to complete

**Comment by rickbergfalk** [comment]
I went ahead and deleted 6.4.2 from Docker Hub. latest, 6, and 6.4 tags will be replaced with working builds
