### ISSUE TITLE
Clickhouse query runs error when the sql starts with comment block

### ISSUE THREAD

**Issue by dengc367** [sqlpad/sqlpad#990]
@rickbergfalk query runs error when the sql has the comment at the beginning, like the following sql: 
```sql
-- comment line at the beginning
-- comment line block
with '2021-01-01' as d
select d
```

**Comment by rickbergfalk** [comment]
@dengc367 merged a fix for this. Want to try this out in `latest` and see if you can break it? :)

**Comment by dengc367** [comment]
Yeah, I have tested successfully. Thanks. @rickbergfalk
