### ISSUE TITLE
Ability to embed the entire application in an iframe?

### ISSUE THREAD

**Issue by ytsaytak** [sqlpad/sqlpad#992]
Hello,

I have been attempting put the entire application in an iframe without much success. It loads, but cannot get through the sign in screen. Is there a security setting to update?

**Comment by rickbergfalk** [comment]
Hi @ytsaytak - if you want to disable the loading screen you can disable auth https://sqlpad.github.io/sqlpad/#/authentication?id=no-authentication

**Comment by ytsaytak** [comment]
Thank you so much!

**Comment by packamn** [comment]
Hi @ytsaytak .... i am also trying to emebed sqlpad in an iftame inside another webapp.... can you pls suggest how to load the sqlpad in an iframe.... should the sqlpad first be hosted on a server and use the address as src for the iframe ?
